spring:
  ai:
    azure:
      openai:
        api-key: ${AZURE_OPENAI_API_KEY:}
        endpoint: ${AZURE_OPENAI_ENDPOINT:}
        chat:
          options:
            deployment-name: ${AZURE_OPENAI_CHAT_DEPLOYMENT:gpt-4o-mini}
            temperature: ${AZURE_OPENAI_TEMPERATURE:0.2}
            max-tokens: ${AZURE_OPENAI_MAX_TOKENS:512}
        embedding:
          options:
            deployment-name: ${AZURE_OPENAI_EMBED_DEPLOYMENT:text-embedding-3-small}
    client:
      connect-timeout: 10s
      read-timeout: 10s
    retry:
      on-http-statuses: 429,500,502,503,504
