spring:
  ai:
    openai:
      api-key: ${PROVIDER_API_KEY:}
      base-url: ${PROVIDER_BASE_URL:https://api.deepseek.com}
      chat:
        options:
          model: ${PROVIDER_CHAT_MODEL:gpt-4o-mini}
          temperature: ${PROVIDER_TEMPERATURE:0.2}
          max-tokens: ${PROVIDER_MAX_TOKENS:512}
      embedding:
        options:
          model: ${PROVIDER_EMBED_MODEL:text-embedding-3-small}
    client:
      connect-timeout: 10s
      read-timeout: 10s
    retry:
      on-http-statuses: 429,500,502,503,504
