spring:
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:}
      chat:
        options:
          model: ${ANTHROPIC_CHAT_MODEL:claude-3-5-sonnet-latest}
          temperature: ${ANTHROPIC_TEMPERATURE:0.2}
          max-tokens: ${ANTHROPIC_MAX_TOKENS:512}
    openai:
      # For embeddings we use OpenAI even on anthropic profile
      api-key: ${OPENAI_API_KEY:}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      embedding:
        options:
          model: ${OPENAI_EMBED_MODEL:text-embedding-3-small}
    client:
      connect-timeout: 10s
      read-timeout: 10s
    retry:
      on-http-statuses: 429,500,502,503,504
