spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/rag_chat_storage}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

# API Key and Rate Limiting
security:
  api-key:
    header: X-API-KEY
    value: ${API_KEY:changeme}
rate-limit:
  requests-per-minute: ${REQUESTS_PER_MINUTE:60}
  burst: ${RATE_BURST:20}

# CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PATCH,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
