logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.rag.chatstorage: DEBUG

spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:h2:mem:rag;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        id:
          new_generator_mappings: true
  liquibase:
    contexts: dev

  jackson:
    serialization:
      write-dates-as-timestamps: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${PORT:8080}
cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PATCH,DELETE,OPTIONS
  allowed-headers: "*"

# Distributed rate limiting
ratelimit:
  enabled: true
  # Enable Redis-backed distributed rate limiting only when explicitly requested.
  # Local in-memory rate limiting remains active regardless of this flag.
  redisEnabled: ${RATELIMIT_REDIS_ENABLED:false}
  #  For containerized deployments, the value of REDIS_HOST should be set to the container name.
  host: localhost
  port: 6379
  ssl: false
