spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/rag_chat_storage}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL:gpt-4o-mini}
      embedding:
        options:
          model: ${OPENAI_EMBED_MODEL:text-embedding-3-small}

server:
  port: ${PORT:8080}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: db
  endpoints:
    web:
      exposure:
        include: health,info

# API Key and Rate Limiting
security:
  api-key:
    header: X-API-KEY
    value: ${API_KEY:changeme}
rate-limit:
  requests-per-minute: ${REQUESTS_PER_MINUTE:60}
  burst: ${RATE_BURST:20}

# CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PATCH,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
