spring:
  datasource:
    url: jdbc:h2:mem:rag;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}
